deployment:
    name: student-app-api
    repCount: 1
    image: vinhbk99nd/student-app-api:0.0.1-SNAPSHOT
    port: 8080
    targetPort: 8080

client:
    name: student-app-client
    repCout: 1
    image: vinhbko99nd/student-app-api:lastest
    port: 8080
    targetPort: 8080

mongo_volume:
    name: mongo-pvc
    storage: 256Mi
mongo:
    name: mongo
    repCount: 1
    image: mongo:3.6.17-xenial
    port: 27017
    targetPort: 7017
