apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongo_volume.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo_volume.storage }}
