apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.client.name }}
spec:
  selector:
    matchLabels: {{include "common.client" . | nindent 6}}
  replicas: 1
  template:
    metadata:
      labels: {{include "common.client" . | nindent 8}}
    spec:
      containers:
        - name: student-app-client
          image: {{ .Values.client.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
