apiVersion: v1
kind: Service
metadata:
  name: student-app-api
spec:
  selector: {{ include "common.fullname" . | nindent 4}}
  ports:
    - port: {{ .Values.deployment.port}}
      protocol: TCP
      targetPort: {{ .Values.deployment.targetport}}
